### ISSUE TITLE
探讨几点

### ISSUE THREAD

**Issue by Ge-yuan-jun** [guliyuan/phone-validate-code-button#1]
功能完善较好，mock 数据的方式很棒，有几点想继续探讨一下：

1. 如何 unmount 这个按钮组件？
2. 如果想要在点击按钮之后即开始倒计时（不管 ajax 请求状态），后端返回错误码，reset 组件状态至初始化该怎么做？
3. 如果我想用户刷新网页之后，仍然能够继续上一次倒计时的时间，这个该怎么做？

**Comment by Ge-yuan-jun** [comment]
补充：

```javascript
return new Promise((resolve, reject) => {
          axios({
            method: 'get',
            url
          }).then((res) => {
            resolve(res);
          }).catch((err) => {
            reject(err);
          });
        });
```

axios 本身返回的就是一个 Promise，在 axios 外面再包一层是基于？

**Comment by guliyuan** [comment]
收到，谢谢~
稍晚统一给答复。




------------------ 原始邮件 ------------------
发件人: "墨白"<notifications@github.com>;
发送时间: 2019年4月15日(星期一) 中午12:20
收件人: "guliyuan/phone-validate-code-button"<phone-validate-code-button@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [guliyuan/phone-validate-code-button] 探讨几点 (#1)




补充：
 return new Promise((resolve, reject) => {           axios({             method: 'get',             url           }).then((res) => {             resolve(res);           }).catch((err) => {             reject(err);           });         });
 
axios 本身返回的就是一个 Promise，在 axios 外面再包一层是基于？

**Comment by guliyuan** [comment]
你好：


1 关于unmount按钮组件


   v-if为false和路由切换时，会触发destroyed钩子函数，销毁组件实例，在这里清除Timer，防止内存泄露。
   注：Timer如果定义在vue实例的data里面，会自动在实例销毁时清除定时器，但是考虑到规范，data定义的应该是页面内用到的状态，所有未采取此方法。


2 在点击按钮之后即开始倒计时（不管 ajax 请求状态），后端返回错误码，reset 组件状态至初始化。
  如下代码：
  监听reset清空动画数组：
    watch:{
        reset(val){
            if(!val) return;
            clearInterval(Timer);
            this.codeNumber = -1;
            // reset两个动画数组置空
            this.animationButton = [];
            this.animationCount = [];
        }
    },




请求修改：
        postValidCode(){
            // pending中，return，防止请求中再次点击
            if(this.pending) return;
            const { phone } = this;
            this.pending = true;
            this.reset = false;
            // 开启计时器，不需要等到接口请求成功
            this.start();
            request.getCode(phone).then(
                res =>{
                    if(res.code !== '1000000'){
                        this.reset = true;
                    }
                    alert(res.message);
                },
                err =>{
                    alert('网络错误 ' + '或者请运行 npm run mock');
                    this.reset = true;
                }
            ).then(_=>{
                this.pending = false;
            });
        },




3 想用户刷新网页之后，仍然能够继续上一次倒计时的时间
    使用localStroge记录当前秒数：
    set：window.setLocalStorage('countNumber', String(this.codeNumber));
    get：Number(window.getLocalStroage('countNumber'));
    localStroge codeNumber优先级大于上级组件传入的Number.
    注意清除localStroge的CodeNumber,比如倒计时为0，组件销毁等情况。
    注：因为vue是spa单页面，所以页面刷新后vuex，keep-alive都失效，不会使用这两种方式。 


4 关于axios
     不要意思，这个问题是我疏忽了~，axios本身返回promise,不需要再嵌套一层promise。
     这样的api方式调用有些繁琐，所以我将axios当做插件引入，每个实例通过this.request请求就可以，比较方便。


     原理是：
        1 vue.use(AxiosPlugin)调用的是AxiosPlugin输出的install方法，如果是对象，需要定义一个install方法，如果是函数，把该函数当做install方法。
        2 install方法的第一个参数是vue的构造器函数，在该参数里通过混入方式加入request方法，因此每个vue实例都有request请求方法。
        3 vue.use(AxiosPlugin) 要在new Vue之前，因为修改的是构造器。
       
    详情请看项目提交记录。
   
    主要代码：
const AxiosPlugin = {
    install(_Vue) {
        _Vue.mixin({
            created() {
                const self = this;
                self.request = AxiosInstance;
            }
        });
    },
}
export default AxiosPlugin;


   
收到请回复~


谷丽媛


------------------ 原始邮件 ------------------
发件人: "墨白"<notifications@github.com>;
发送时间: 2019年4月15日(星期一) 中午12:15
收件人: "guliyuan/phone-validate-code-button"<phone-validate-code-button@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [guliyuan/phone-validate-code-button] 探讨几点 (#1)




功能完善较好，mock 数据的方式很棒，有几点想继续探讨一下：
  
如何 unmount 这个按钮组件？
 
如果想要在点击按钮之后即开始倒计时（不管 ajax 请求状态），后端返回错误码，reset 组件状态至初始化该怎么做？
 
如果我想用户刷新网页之后，仍然能够继续上一次倒计时的时间，这个该怎么做？

**Comment by Ge-yuan-jun** [comment]
已收到回复，我这边没有什么问题了，该 issue 关闭

**Comment by Ge-yuan-jun** [comment]
review 结果已反馈，麻烦耐心等待通知
